kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: startup-script
  namespace: kube-system
  labels:
    app: startup-script
spec:
  template:
    metadata:
      labels:
        app: startup-script
    spec:
      hostPID: true
      containers:
        - name: startup-script
          image: gcr.io/google-containers/startup-script:v1
          securityContext:
            privileged: true
          env:
          - name: STARTUP_SCRIPT
            value: |
              #! /bin/bash

              set -o errexit
              set -o pipefail
              set -o nounset

              if [[ ! -f /etc/kubernetes/manifests/fluentd-es.yaml ]]; then
                cp -a /srv/salt/fluentd-es/fluentd-es.yaml /etc/kubernetes/manifests/
                rm /etc/kubernetes/manifests/fluentd-gcp.yaml
              fi
